---
- name: Creating replication registries
  no_log: true
  uri:
    url: "{{ harbor_external_url }}/api/v2.0/registries"
    validate_certs: no
    method: POST
    user: "admin"
    password: "{{ harbor_admin_password }}"
    body_format: json
    force_basic_auth: yes
    return_content: yes
    status_code:
      - 201
      - 409
    body: "{{ lookup('template', 'templates/api_templates/create_registry.j2') }}"
  register: create_registry_result
  retries: 5
  delay: 10
  until: (create_registry_result.status == 201) or (create_registry_result.status == 409)
  with_items: "{{ harbor_replication_registries }}"
  when: harbor_replication_registries is defined

- name: Get Docker Hub registry info
  no_log: true
  uri:
    url: "{{ harbor_external_url }}/api/v2.0/registries"
    validate_certs: no
    method: GET
    user: "admin"
    password: "{{ harbor_admin_password }}"
    body_format: json
    force_basic_auth: yes
    return_content: yes
    status_code:
      - 200
  register: check_registry_result
  retries: 5
  delay: 10
  until: check_registry_result.status == 200
  when: create_registry_result is defined and harbor_replication_dockerhub_rules is defined

- name: Create replication rules
  include_tasks: replication_rule.yml
  loop: "{{ harbor_replication_dockerhub_rules }}"
  when: harbor_replication_dockerhub_rules is defined
