---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: generic/ubuntu2004
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8088"
    memory: 2048
    cpus: 2
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - cleanup
    - destroy
provisioner:
  name: ansible
verifier:
  name: ansible
